### PR TITLE
Django 3.0 support

### PR DESCRIPTION
**Pull request by CorrosiveKid**
Adds support for Django 3.0

Closes https://github.com/sabricot/django-elasticsearch-dsl/pull/233

### CODE REVIEW

**Comment by CorrosiveKid** [comment]
@sabricot @safwanrahman Please review when you have some time.

**Comment by safwanrahman** [comment]
I think it was created before? https://github.com/sabricot/django-elasticsearch-dsl/pull/230

**Comment by CorrosiveKid** [comment]
@safwanrahman Ah yes it's pretty much the same except this one maintains Python 2 support.

**Comment by Rafalonso** [comment]
Since python 2 is in its EOL, I believe support for it should be dropped.

**Comment by safwanrahman** [comment]
@Rafalonso I dont think so. We still support django 1.11. So it should be supported untill django 1.11 is supported.

**Comment by Rafalonso** [comment]
@safwanrahman django 1.11 would still be supported, just in python 3. But yes, I have changed my mind, there's no reason to drop a version unless it's necessary

**Comment by safwanrahman** [comment]
@Rafalonso Great. I also do not like to drop support for python2 as it will create problem for the legacy applications that need to rely on Python 2 support unless we face any issue that is hard to solve in python 2.

**Comment by safwanrahman** [comment]
Thanks for the contribution. But  #230 seems to be opened before this one. So closing it.

**Pull request closed without merging**
