### PR TITLE
Add support for Django 3.0

### PR DESCRIPTION
**Pull request by noamkush**

### CODE REVIEW

**Comment by safwanrahman** [comment]
Great! 💯 So fast it have been made. I did not know django 3.0 released before seeing the PR.

I will take a closer look and we will be able to merge this. 🚀

**Comment by safwanrahman** [comment]
@noamkush Can you add the Python 2 support and dont remove it?

**Comment by noamkush** [comment]
Okay, I pushed a version that doesn't drop Python 2.7 support

**Comment by safwanrahman** [comment]
Looks Good, test passes! r+ from my end! 🤘🚀🤩🚢📦

**Comment by telephono** [comment]
Will there be a backport to django-elasticsearch-dsl 6.4.x ?

**Comment by barseghyanartur** [comment]
@telephono:

See #241

**Pull request merged**
