### PR TITLE
Adding support for Postgresql JSONField

### PR DESCRIPTION
**Pull request by safwanrahman**

### CODE REVIEW

**Comment by safwanrahman** [comment]
As could not find any reviewer, I am good to have this r+

**Comment by andreasnuesslein** [comment]
@safwanrahman does it work for you out of the box now?
I still am getting a list of empty dicts (with the psql-db-value being `{"2": "sadf", "foo": "baaar"}`):

```json
"negotiation_status": [
  {}
  {}
],
```



Only when I do:
```
    def prepare_negotiation_status(self, instance):
        return instance.negotiation_status
```

I get:
```json
"negotiation_status": {
  "2": "sadf",
  "foo": "baaar"
},
```

**Comment by safwanrahman** [comment]
@andreasnuesslein Oops, Sorry. I expected to have it working normally. I need to fix it before releasing new version. Are you using master branch? It is high likely that there is error code.

**Comment by andreasnuesslein** [comment]
@safwanrahman Yeah I tried it with master but the same thing happens with the current stable pip release 7.1.0 , after setting `negotiation_status = fields.ObjectField()`.

**Comment by andreasnuesslein** [comment]
mentioning https://github.com/sabricot/django-elasticsearch-dsl/issues/36 here for bidirectional link

**Comment by andreasnuesslein** [comment]
So I dove into the code and figured out you should just replace `ObjectField` with `DEDField`.

**Comment by oehrlein** [comment]
@andreasnuesslein I'm having a similar issue. Where did you replace `ObjectField` with `DEDField`?

**Comment by oehrlein** [comment]
@andreasnuesslein Got it, no problem! I was just curious since I was working on (and found) a solution to the "list of empty dicts" issue you had above.

**Pull request merged**
