### PR TITLE
Import Document not DocType

### PR DESCRIPTION
**Pull request by ogiogi93**
~I think `from django_elasticsearch_dsl import Document` is not a correct path  🤔~

just import Document not DocType

### CODE REVIEW

**Comment by safwanrahman** [comment]
LGTM. r+

**Comment by Acetonen** [comment]
@safwanrahman you already broke my production with this))) 
image

i install django_elasticsearch_dsl directly from git(  because pip version don't update

**Comment by safwanrahman** [comment]
@Acetonen Sorry. How it broke your production?

**Comment by Acetonen** [comment]
@safwanrahman like this:

image

I've fixed it, but I think you have to leave here:

image

this: 
`from .documents import Document, DocType`
until you get stable and updated PIP version

**Comment by safwanrahman** [comment]
@Acetonen You must install a specific version as mentioned in the doc not the master branch.
`pip install https://github.com/sabricot/django-elasticsearch-dsl/archive/6.4.1.tar.gz`

**Comment by Acetonen** [comment]
@safwanrahman yea, my fault(

**Pull request merged**
